### ISSUE TITLE
Error 500 for one page

### ISSUE THREAD

**Issue by jodeq** [frappe/frappe_io#108]
this url : https://frappe.io/docs/user/en/guides/automated-testing/qunit-testing
give error 500

**Comment by jodeq** [comment]
```
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 45, in render
    data = render_page_by_language(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 139, in render_page_by_language
    return render_page(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 155, in render_page
    return build(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 162, in build
    return build_page(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 181, in build_page
    html = frappe.render_template(context.source, context)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/jinja.py", line 74, in render_template
    throw("Illegal template")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 339, in throw
    msgprint(msg, raise_exception=exc, title=title, indicator='red')
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 325, in msgprint
    _raise_exception()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 298, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.ValidationError: Illegal template

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/context.py", line 48, in update_controller_context
    ret = module.get_context(context)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/www/error.py", line 12, in get_context
    print(frappe.get_traceback().encode("utf-8"))
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 69, in application
    response = frappe.website.render.render()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 72, in render
    data = render_page(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 155, in render_page
    return build(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 162, in build
    return build_page(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 175, in build_page
    context = get_context(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/context.py", line 28, in get_context
    context = build_context(context)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/context.py", line 98, in build_context
    update_controller_context(context, context.controller)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/context.py", line 55, in update_controller_context
    frappe.errprint(frappe.utils.get_traceback())
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 262, in errprint
    print(msg)
BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by ddavidebor** [comment]
closing for #283
