### ISSUE TITLE
Broken github login

### ISSUE THREAD

**Issue by ddavidebor** [frappe/frappe_io#286]
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 62, in application
    response = frappe.api.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/api.py", line 58, in handle
    return frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 63, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1074, in call
    return fn(*args, **newargs)
TypeError: login_via_github() missing 1 required positional argument: 'code'

BTW error code should NOT be exposed for login functions!

**Comment by revant** [comment]
The redirect in response has details of error

```
https://frappe.erpnext.com/api/method/frappe.www.login.login_via_github?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdeveloper.github.com%2Fapps%2Fmanaging-oauth-apps%2Ftroubleshooting-authorization-request-errors%2F%23redirect-uri-mismatch&state=eyJzaXRlIjogImh0dHBzOi8vZnJhcHBlLmlvIiwgInRva2VuIjogImMzOWYzNTNmYjU4MjFiN2UyOThmYWI2ZDdhNmJhOTI3YjU2NGE2MDg2YTY2ZTdkOTg5NDQyMWNmIiwgInJlZGlyZWN0X3RvIjogbnVsbH0%3D
```

**Comment by ddavidebor** [comment]
I noticed but I am not going to work on this issue, this is for Frappe to fix

**Comment by ddavidebor** [comment]
Closed in favour of https://github.com/frappe/frappe_docs/issues/74
